{{- if .Values.apps.service.account.login.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-login
spec:
  selector:
    matchLabels:
      app: account-login
  strategy:
    type: Recreate
  revisionHistoryLimit: {{ .Values.apps.service.account.login.deployment.revisions }}
  template:
    metadata:
      labels:
        app: account-login
    spec:
      imagePullSecrets:
        {{- toYaml .Values.apps.service.account.login.deployment.ips | nindent 8 }}
      containers:
        - name: account-login
          image: {{ .Values.meta.repo }}/account-login:{{ .Values.meta.tag }}
          imagePullPolicy: Always
          env:
            {{- toYaml .Values.apps.service.account.login.deployment.env | nindent 12 }}
{{ end }}
