version: 0.3

env:
  REG_BASE: harbor.chinook.k8s.voidpointergroup.com
  REG_PROJ: freediving-family
  REG_USER: robot-freediving-family+ci
  REG_PASS: qSxgkZpMfKJ1oBRHDeBEk6eunTjiP4En

.services: &services
  - env:
      APP: apofed
      FLAVOR: graphql
  - env:
      APP: account
      FLAVOR: login
  - env:
      APP: account
      FLAVOR: graphql
  - env:
      APP: account
      FLAVOR: worker
  - env:
      APP: certification
      FLAVOR: graphql
  - env:
      APP: event
      FLAVOR: graphql

chains:
  cmd:
    matrix:
      - *services
    tasks:
      - script: |
          cd code/backend/apps/$APP
          {{ cmd }}

  install:
    matrix:
      - *services
    tasks:
      - script: |
          cd code/backend/apps/$APP
          npm i

  codegen:
    pre:
      - install
    matrix:
      - *services
    tasks:
      - script: |
          cd code/backend/apps/$APP
          npm run codegen || true

  prepare:
    pre:
      - codegen
    workdir: code/backend
    tasks:
      - script: |
          cd libs/bus/ts
          npm i
          npm run codegen
      - script: |
          cd libs/shared
          npm i
