{{- if .Values.apps.service.certification.graphql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: certification-graphql
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: certification-graphql
{{ end }}
