{{- if .Values.apps.service.event.graphql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: event-graphql
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: event-graphql
{{ end }}
