{{- if .Values.apps.service.apofed.graphql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: apofed-graphql
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apofed-graphql
{{ end }}
