meta:
  repo: harbor.chinook.k8s.voidpointergroup.com/freediving-family
  tag: "{{ meta.tag }}"

system:
  ips: "default"
  config:
    yaml: |-
      database:
        mongodb:
          url: "mongodb://freediving-family-mongodb-headless:27017"
      bus:
        nats:
          url: "http://marketplace-nats:4222"

apps:
  service:
    apofed:
      graphql:
        enabled: true
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_SERVICES
              value: "http://account-graphql:8080"
        hpa:
          min: 2
          max: 4
          cpu: 50

    account:
      graphql:
        enabled: true
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_SYSCONF
              valueFrom:
                secretKeyRef:
                  name: "system-config"
                  key: "yaml"
                  optional: false
        hpa:
          min: 2
          max: 4
          cpu: 50
      login:
        enabled: true
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_SYSCONF
              valueFrom:
                secretKeyRef:
                  name: "system-config"
                  key: "yaml"
                  optional: false
        hpa:
          min: 2
          max: 4
          cpu: 50
      worker:
        enabled: true
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_LOG_LEVEL
              value: "INFO"
            - name: APP_SYSCONF
              valueFrom:
                secretKeyRef:
                  name: "system-config"
                  key: "yaml"
                  optional: false
        hpa:
          min: 2
          max: 4
          cpu: 50

nats:
  enabled: true
  nats:
    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 1Gi
      fileStorage:
        enabled: true
        storageDirectory: /data
        size: 8Gi
        # storageClassName: ""
        accessModes:
          - ReadWriteOnce
  cluster:
    enabled: true
    replicas: 3

mongodb:
  enabled: true
  auth:
    enabled: false
    rootUser: root
    rootPassword: ""
  architecture: replicaset
  replicaCount: 2
  arbiter:
    enabled: false
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 16Gi
