meta:
  repo: harbor.chinook.k8s.voidpointergroup.com/freediving-family
  tag: "{{ meta.tag }}"

system:
  config:
    yaml: |-
      database:
        mongodb:
          url: "mongodb://freediving-family-mongodb-headless:27017"
      bus:
        nats:
          url: "http://marketplace-nats:4222"

apps:
  service:
    frontend:
      enabled: true
      service:
        nodeport: { { frontend.service.nodeport.http } }
      deployment:
        ips:
          - name: internal-registry-marketplace
        revisions: 0
        env:
          - name: MARKETPLACE_API_BASE
            value: "https://api-{{ mcamp.infra.rooturl }}.marketplace.nexteraanalytics.com"
          - name: MARKETPLACE_GRAPHQL_URL
            value: "https://api-{{ mcamp.infra.rooturl }}.marketplace.nexteraanalytics.com/graphql"
      hpa:
        min: 2
        max: 4
        cpu: 50

    apofed:
      graphql:
        enabled: true
        service:
          nodeport: { { apofed.service.nodeport.http } }
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_SERVICES
              value: "http://ledger-graphql:8080/query,http://account-graphql:8080/query,http://application-graphql:8080/query,http://license-graphql:8080/query,http://template-graphql:8080/query"
            - name: APP_KEYCLOAK_REALM_URL
              value: "https://auth-{{ mcamp.infra.rooturl }}.marketplace.nexteraanalytics.com/auth/realms/mcamp"
        hpa:
          min: 2
          max: 4
          cpu: 50

    account:
      graphql:
        enabled: true
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_LOG_LEVEL
              value: "INFO"
            - name: APP_HTTP_LOG_FORMAT
              value: '{"time":"${time_rfc3339_nano}","id":"${id}","remote_ip":"${remote_ip}","host":"${host}","user_agent":"${user_agent}","method":"${method}","path":"${path}","uri":"${uri}","referer":"${referer}","status":${status},"latency":${latency},"latency_human":"${latency_human}","bytes_in":${bytes_in},"bytes_out":${bytes_out},"headers":"{"Authorization": "${header:Authorization}"}","protocol":"${protocol}"}'
            - name: APP_SYSCONF
              valueFrom:
                secretKeyRef:
                  name: "system-config"
                  key: "yaml"
                  optional: false
        hpa:
          min: 2
          max: 4
          cpu: 50
      login:
        enabled: true
        service:
          nodeport: { { account.login.nodeport.http } }
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_LOG_LEVEL
              value: "INFO"
            - name: APP_HTTP_LOG_FORMAT
              value: '{"time":"${time_rfc3339_nano}","id":"${id}","remote_ip":"${remote_ip}","host":"${host}","user_agent":"${user_agent}","method":"${method}","path":"${path}","uri":"${uri}","referer":"${referer}","status":${status},"latency":${latency},"latency_human":"${latency_human}","bytes_in":${bytes_in},"bytes_out":${bytes_out},"headers":"{"Authorization": "${header:Authorization}"}","protocol":"${protocol}"}'
            - name: APP_SYSCONF
              valueFrom:
                secretKeyRef:
                  name: "system-config"
                  key: "yaml"
                  optional: false
        hpa:
          min: 2
          max: 4
          cpu: 50
      worker:
        enabled: true
        deployment:
          ips:
            - name: internal-registry-marketplace
          revisions: 0
          env:
            - name: APP_LOG_LEVEL
              value: "INFO"
            - name: APP_SYSCONF
              valueFrom:
                secretKeyRef:
                  name: "system-config"
                  key: "yaml"
                  optional: false
        hpa:
          min: 2
          max: 4
          cpu: 50

nats:
  enabled: true
  nats:
    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 1Gi
      fileStorage:
        enabled: true
        storageDirectory: /data
        size: 8Gi
        # storageClassName: ""
        accessModes:
          - ReadWriteOnce
  cluster:
    enabled: true
    replicas: 3

mongodb:
  enabled: true
  auth:
    enabled: false
    rootUser: root
    rootPassword: ""
  architecture: replicaset
  replicaCount: 2
  arbiter:
    enabled: false
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 24Gi
