{{- if .Values.apps.service.account.graphql.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: account-graphql
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account-graphql
  minReplicas: {{ .Values.apps.service.account.graphql.hpa.min }}
  maxReplicas: {{ .Values.apps.service.account.graphql.hpa.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apps.service.account.graphql.hpa.cpu }}
{{ end }}
