{{- if .Values.apps.service.account.graphql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: account-graphql
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: account-graphql
{{ end }}
