name: release
on:
  push:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: "version"
#         required: true

env:
  COMPLATE_DEB: https://github.com/replicadse/complate/releases/download/0.10.6/complate_0.10.6_amd64.deb
  NEOMAKE_DEB: https://github.com/voidpointergroup/neomake/releases/download/0.3.8/neomake_0.3.8_amd64.deb

jobs:
  version:
    name: version
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.export.outputs.version }}
    steps:
      - id: export
        run: 'printf "version=$(date +%s)" >> $GITHUB_OUTPUT'

  images:
    name: harbor (${{ needs.version.outputs.version }} - ${{ matrix.app }}/${{ matrix.flavor }})
    runs-on: ubuntu-latest
    needs: version
    strategy:
      matrix:
        include:
          - app: "apofed"
            flavor: "graphql"
          - app: "account"
            flavor: "graphql"
          - app: "account"
            flavor: "login"
          - app: "account"
            flavor: "worker"
          - app: "certification"
            flavor: "graphql"
          - app: "event"
            flavor: "graphql"
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -LX GET -o ./complate.deb $COMPLATE_DEB
          sudo apt-get install -y ./complate.deb
          curl -LX GET -o ./neomake.deb $COMPLATE_DEB
          sudo apt-get install -y ./neomake.deb
      - name: publish image
        run: |
          neomake x -c image -a app=${{ matrix.app }} -a flavor=${{ matrix.flavor }} -a version=0.1.${{ needs.version.outputs.version }}

  helm:
    name: harbor (${{ needs.version.outputs.version }} - helm chart)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - version
      - images
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -LX GET -o ./complate.deb $COMPLATE_DEB
          sudo apt-get install -y ./complate.deb
          curl -LX GET -o ./neomake.deb $COMPLATE_DEB
          sudo apt-get install -y ./neomake.deb
      - name: install dependencies
        run: "curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
      - name: publish helm
        run: |
          ls -algh
          neomake x -c helm -a chart=freediving-family -a version=0.1.${{ needs.version.outputs.version }}
