name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true

jobs:
  images:
    name: harbor (${{ github.event.inputs.version }} - ${{ matrix.app }}/${{ matrix.flavor }})
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: "apofed"
            flavor: "graphql"
          - app: "account"
            flavor: "graphql"
          - app: "account"
            flavor: "login"
          - app: "account"
            flavor: "worker"
    steps:
      - uses: actions/checkout@v3
      - name: install rust
        run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      - name: install tools
        run: "cargo install neomake"
      - name: publish image
        run: |
          neomake x -c image -a app=${{ matrix.app }} -a flavor=${{ matrix.flavor }} -a version=${{ github.event.inputs.version }}

  helm:
    name: harbor (${{ github.event.inputs.version }} - helm chart)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: images
    steps:
      - uses: actions/checkout@v3
      - name: install rust
        run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      - name: install tools
        run: |
          cargo install neomake
          cargo install complate
      - name: install dependencies
        run: "curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
      - name: publish helm
        run: |
          ls -algh
          neomake x -c helm -a chart=freediving-family -a version=${{ github.event.inputs.version }}
